# production:
#   domain: "addev@50.57.98.187"
#   deploy_to: "/var/www/audiodeluxe.com/sites/all"
#   repository: "git@github.com:centresource/audiodeluxe.git"
#   branch: "master"

production:
  domain:
    name: "bricks@bricksites.info"
    ssh_options: "-p 2222"
  deploy_to: "~/public_html/micah/micahredding.com"
  repository: "git@github.com:micahredding/micahredding.com.git"
  branch: "master"
